In [1]:
from google.colab import files

uploaded = files.upload()

Saving SuperMarket Analysis.csv to SuperMarket Analysis.csv

In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("SuperMarket Analysis.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [5]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

In [6]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn Names:")
print(df.columns.tolist())

Number of rows: 1000
Number of columns: 17

Column Names:
['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date', 'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income', 'Rating']

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

In [8]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Invoice ID                 0
Branch                     0
City                       0
Customer type              0
Gender                     0
Product line               0
Unit price                 0
Quantity                   0
Tax 5%                     0
Sales                      0
Date                       0
Time                       0
Payment                    0
cogs                       0
gross margin percentage    0
gross income               0
Rating                     0
dtype: int64

In [9]:
duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0

In [10]:
df.columns = [
    'Invoice_ID',
    'Branch',
    'City',
    'Customer_Type',
    'Gender',
    'Product_Line',
    'Unit_Price',
    'Quantity',
    'Tax_5',
    'Sales',
    'Date',
    'Time',
    'Payment',
    'COGS',
    'Gross_Margin_Percentage',
    'Gross_Income',
    'Rating'
]

print(df.columns.tolist())

['Invoice_ID', 'Branch', 'City', 'Customer_Type', 'Gender', 'Product_Line', 'Unit_Price', 'Quantity', 'Tax_5', 'Sales', 'Date', 'Time', 'Payment', 'COGS', 'Gross_Margin_Percentage', 'Gross_Income', 'Rating']

In [11]:
text_columns = [
    'Invoice_ID',
    'Branch',
    'City',
    'Customer_Type',
    'Gender',
    'Product_Line',
    'Payment'
]

for col in text_columns:
    df[col] = df[col].str.strip()

print("Text data cleaned successfully!")

Text data cleaned successfully!

In [12]:
for col in [
    'Branch',
    'City',
    'Customer_Type',
    'Gender',
    'Product_Line',
    'Payment'
]:
    print("\n", col)
    print(df[col].unique())

 Branch
['Alex' 'Giza' 'Cairo']

 City
['Yangon' 'Naypyitaw' 'Mandalay']

 Customer_Type
['Member' 'Normal']

 Gender
['Female' 'Male']

 Product_Line
['Health and beauty' 'Electronic accessories' 'Home and lifestyle'
 'Sports and travel' 'Food and beverages' 'Fashion accessories']

 Payment
['Ewallet' 'Cash' 'Credit card']

In [13]:
df['Date'] = pd.to_datetime(
    df['Date'],
    errors='coerce'
)

df['Time'] = pd.to_datetime(
    df['Time'],
    format='%H:%M:%S',
    errors='coerce'
).dt.time

print(df[['Date', 'Time']].head())

        Date Time
0 2019-01-05  NaT
1 2019-03-08  NaT
2 2019-03-03  NaT
3 2019-01-27  NaT
4 2019-02-08  NaT

In [14]:
print(df['Date'].dtype)

datetime64[ns]

In [19]:
df['Year'] = df['Date'].dt.year

df['Month'] = df['Date'].dt.month

df['Month_Name'] = df['Date'].dt.month_name()

df['Quarter'] = df['Date'].dt.quarter

df['Day'] = df['Date'].dt.day

df['Day_Name'] = df['Date'].dt.day_name()

df['Day_Of_Week'] = df['Date'].dt.dayofweek + 1

In [20]:
df[
    [
        'Date',
        'Year',
        'Month',
        'Month_Name',
        'Quarter',
        'Day',
        'Day_Name',
        'Day_Of_Week'
    ]
].head()

        Date  Year  Month Month_Name  Quarter  Day  Day_Name  Day_Of_Week
0 2019-01-05  2019      1    January        1    5  Saturday            6
1 2019-03-08  2019      3      March        1    8    Friday            5
2 2019-03-03  2019      3      March        1    3    Sunday            7
3 2019-01-27  2019      1    January        1   27    Sunday            7
4 2019-02-08  2019      2   February        1    8    Friday            5

In [23]:
df['Hour'] = df['Time'].apply(
    lambda x: x.hour if pd.notnull(x) else None
)

In [27]:
def get_time_period(hour):

    if pd.isnull(hour):
        return 'Unknown'

    elif hour < 12:
        return 'Morning'

    elif hour < 17:
        return 'Afternoon'

    elif hour < 21:
        return 'Evening'

    else:
        return 'Night'


df['Time_Period'] = df['Hour'].apply(get_time_period)

In [28]:
df[['Time', 'Hour', 'Time_Period']].head(10)

  Time  Hour Time_Period
0  NaT  None     Unknown
1  NaT  None     Unknown
2  NaT  None     Unknown
3  NaT  None     Unknown
4  NaT  None     Unknown
5  NaT  None     Unknown
6  NaT  None     Unknown
7  NaT  None     Unknown
8  NaT  None     Unknown
9  NaT  None     Unknown

In [29]:
df['Calculated_COGS'] = (
    df['Unit_Price'] * df['Quantity']
)

df['Calculated_Tax'] = (
    df['Calculated_COGS'] * 0.05
)

df['Calculated_Gross_Profit'] = (
    df['Sales'] - df['Calculated_COGS']
)

In [30]:
df[
    [
        'Unit_Price',
        'Quantity',
        'Sales',
        'Calculated_COGS',
        'Calculated_Tax',
        'Calculated_Gross_Profit'
    ]
].head()

,Unit_Price,Quantity,Sales,Calculated_COGS,Calculated_Tax,Calculated_Gross_Profit
0,74.69,7,548.9715,522.83,26.1415,26.1415
1,15.28,5,80.2200,76.40,3.8200,3.8200
2,46.33,7,340.5255,324.31,16.2155,16.2155
3,58.22,8,489.0480,465.76,23.2880,23.2880
4,86.31,7,634.3785,604.17,30.2085,30.2085

In [32]:
valid_sales = df['Sales'] > 0

valid_quantity = df['Quantity'] > 0

valid_price = df['Unit_Price'] > 0

valid_rating = df['Rating'].between(1, 10)

all_valid = (
    valid_sales &
    valid_quantity &
    valid_price &
    valid_rating
)

In [34]:
df_valid = df[all_valid].copy()

df_invalid = df[~all_valid].copy()

print("Total Records:", len(df))
print("Valid Records:", len(df_valid))
print("Invalid Records:", len(df_invalid))

Total Records: 1000
Valid Records: 1000
Invalid Records: 0

In [36]:
if df_invalid.empty:
    print("All records passed validation!")
else:
    print("Invalid records found:")
    display(df_invalid.head())

All records passed validation!

In [37]:
dim_date = df_valid[
    [
        'Date',
        'Year',
        'Month',
        'Month_Name',
        'Quarter',
        'Day',
        'Day_Name',
        'Day_Of_Week'
    ]
].drop_duplicates().copy()

dim_date = dim_date.sort_values('Date').reset_index(drop=True)

dim_date.insert(
    0,
    'Date_Key',
    range(1, len(dim_date) + 1)
)

display(dim_date.head())

,Date_Key,Date,Year,Month,Month_Name,Quarter,Day,Day_Name,Day_Of_Week
0,1,2019-01-01,2019,1,January,1,1,Tuesday,2
1,2,2019-01-02,2019,1,January,1,2,Wednesday,3
2,3,2019-01-03,2019,1,January,1,3,Thursday,4
3,4,2019-01-04,2019,1,January,1,4,Friday,5
4,5,2019-01-05,2019,1,January,1,5,Saturday,6

In [38]:
dim_branch = df_valid[
    ['Branch', 'City']
].drop_duplicates().reset_index(drop=True)

dim_branch.insert(
    0,
    'Branch_Key',
    range(1, len(dim_branch) + 1)
)

display(dim_branch)

   Branch_Key Branch       City
0           1   Alex     Yangon
1           2   Giza  Naypyitaw
2           3  Cairo   Mandalay

In [39]:
dim_product = df_valid[
    ['Product_Line']
].drop_duplicates().reset_index(drop=True)

dim_product.insert(
    0,
    'Product_Key',
    range(1, len(dim_product) + 1)
)

display(dim_product)

   Product_Key            Product_Line
0            1       Health and beauty
1            2  Electronic accessories
2            3      Home and lifestyle
3            4       Sports and travel
4            5      Food and beverages
5            6     Fashion accessories

In [40]:
dim_customer = df_valid[
    [
        'Customer_Type',
        'Gender'
    ]
].drop_duplicates().reset_index(drop=True)

dim_customer.insert(
    0,
    'Customer_Key',
    range(1, len(dim_customer) + 1)
)

display(dim_customer)

   Customer_Key Customer_Type  Gender
0             1        Member  Female
1             2        Normal  Female
2             3        Member    Male
3             4        Normal    Male

In [41]:
dim_payment = df_valid[
    ['Payment']
].drop_duplicates().reset_index(drop=True)

dim_payment.insert(
    0,
    'Payment_Key',
    range(1, len(dim_payment) + 1)
)

display(dim_payment)

   Payment_Key      Payment
0            1      Ewallet
1            2         Cash
2            3  Credit card

In [42]:
fact_sales = df_valid.copy()

In [43]:
fact_sales = fact_sales.merge(
    dim_date[['Date_Key', 'Date']],
    on='Date',
    how='left'
)

In [44]:
fact_sales = fact_sales.merge(
    dim_branch,
    on=['Branch', 'City'],
    how='left'
)

In [45]:
fact_sales = fact_sales.merge(
    dim_product,
    on='Product_Line',
    how='left'
)

In [46]:
fact_sales = fact_sales.merge(
    dim_customer,
    on=['Customer_Type', 'Gender'],
    how='left'
)

In [47]:
fact_sales = fact_sales.merge(
    dim_payment,
    on='Payment',
    how='left'
)

In [48]:
fact_sales = fact_sales[
    [
        'Invoice_ID',
        'Date_Key',
        'Branch_Key',
        'Product_Key',
        'Customer_Key',
        'Payment_Key',
        'Time',
        'Hour',
        'Time_Period',
        'Unit_Price',
        'Quantity',
        'Tax_5',
        'Sales',
        'COGS',
        'Gross_Margin_Percentage',
        'Gross_Income',
        'Rating'
    ]
]

display(fact_sales.head())

,Invoice_ID,Date_Key,Branch_Key,Product_Key,Customer_Key,Payment_Key,Time,Hour,Time_Period,Unit_Price,Quantity,Tax_5,Sales,COGS,Gross_Margin_Percentage,Gross_Income,Rating
0,750-67-8428,5,1,1,1,1,NaT,None,Unknown,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,226-31-3081,67,2,2,2,2,NaT,None,Unknown,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,631-41-3108,62,1,3,2,3,NaT,None,Unknown,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,123-19-1176,27,1,1,1,1,NaT,None,Unknown,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,373-73-7910,39,1,4,1,1,NaT,None,Unknown,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3

In [49]:
print("FactSales Rows:", len(fact_sales))
print("FactSales Columns:", len(fact_sales.columns))

FactSales Rows: 1000
FactSales Columns: 17

In [50]:
key_columns = [
    'Date_Key',
    'Branch_Key',
    'Product_Key',
    'Customer_Key',
    'Payment_Key'
]

print(fact_sales[key_columns].isnull().sum())

Date_Key        0
Branch_Key      0
Product_Key     0
Customer_Key    0
Payment_Key     0
dtype: int64

In [51]:
import os

os.makedirs(
    'supermarket_data_warehouse',
    exist_ok=True
)

In [52]:
dim_date.to_csv(
    'supermarket_data_warehouse/dim_date.csv',
    index=False
)

dim_branch.to_csv(
    'supermarket_data_warehouse/dim_branch.csv',
    index=False
)

dim_product.to_csv(
    'supermarket_data_warehouse/dim_product.csv',
    index=False
)

dim_customer.to_csv(
    'supermarket_data_warehouse/dim_customer.csv',
    index=False
)

dim_payment.to_csv(
    'supermarket_data_warehouse/dim_payment.csv',
    index=False
)

fact_sales.to_csv(
    'supermarket_data_warehouse/fact_sales.csv',
    index=False
)

print("ETL pipeline completed successfully!")

ETL pipeline completed successfully!

In [53]:
print("===== DATA WAREHOUSE SUMMARY =====")

print("DimDate     :", dim_date.shape)
print("DimBranch   :", dim_branch.shape)
print("DimProduct  :", dim_product.shape)
print("DimCustomer :", dim_customer.shape)
print("DimPayment  :", dim_payment.shape)
print("FactSales   :", fact_sales.shape)

===== DATA WAREHOUSE SUMMARY =====
DimDate     : (89, 9)
DimBranch   : (3, 3)
DimProduct  : (6, 2)
DimCustomer : (4, 3)
DimPayment  : (3, 2)
FactSales   : (1000, 17)

In [54]:
display(fact_sales.head())

,Invoice_ID,Date_Key,Branch_Key,Product_Key,Customer_Key,Payment_Key,Time,Hour,Time_Period,Unit_Price,Quantity,Tax_5,Sales,COGS,Gross_Margin_Percentage,Gross_Income,Rating
0,750-67-8428,5,1,1,1,1,NaT,None,Unknown,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,226-31-3081,67,2,2,2,2,NaT,None,Unknown,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,631-41-3108,62,1,3,2,3,NaT,None,Unknown,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,123-19-1176,27,1,1,1,1,NaT,None,Unknown,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,373-73-7910,39,1,4,1,1,NaT,None,Unknown,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3

In [55]:
# Reload original Time values from CSV
original_df = pd.read_csv("SuperMarket Analysis.csv")

# Convert Time correctly
df['Time'] = pd.to_datetime(
    original_df['Time'].astype(str).str.strip(),
    format='%H:%M',
    errors='coerce'
).dt.time

# Check result
print(df['Time'].head())
print("\nMissing Time values:", df['Time'].isna().sum())

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Time, dtype: datetime64[ns]

Missing Time values: 1000

In [56]:
# Check original time format first
print(original_df['Time'].head(10))

0     1:08:00 PM
1    10:29:00 AM
2     1:23:00 PM
3     8:33:00 PM
4    10:37:00 AM
5     6:30:00 PM
6     2:36:00 PM
7    11:38:00 AM
8     5:15:00 PM
9     1:27:00 PM
Name: Time, dtype: object

In [57]:
# Convert Time correctly using HH:MM:SS format
df['Time'] = pd.to_datetime(
    original_df['Time'].astype(str).str.strip(),
    format='%H:%M:%S',
    errors='coerce'
).dt.time

print(df['Time'].head())
print("Missing Time values:", df['Time'].isna().sum())

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: Time, dtype: datetime64[ns]
Missing Time values: 1000

In [58]:
# Check raw time values
raw_time = original_df['Time'].astype(str).str.strip()

print("Original Time values:")
print(raw_time.head(10).tolist())

# Parse different/mixed time formats automatically
parsed_time = pd.to_datetime(
    raw_time,
    format='mixed',
    errors='coerce'
)

df['Time'] = parsed_time.dt.time

print("\nConverted Time values:")
print(df['Time'].head(10))

print("\nMissing Time values:", df['Time'].isna().sum())

Original Time values:
['1:08:00 PM', '10:29:00 AM', '1:23:00 PM', '8:33:00 PM', '10:37:00 AM', '6:30:00 PM', '2:36:00 PM', '11:38:00 AM', '5:15:00 PM', '1:27:00 PM']

Converted Time values:
0    13:08:00
1    10:29:00
2    13:23:00
3    20:33:00
4    10:37:00
5    18:30:00
6    14:36:00
7    11:38:00
8    17:15:00
9    13:27:00
Name: Time, dtype: object

Missing Time values: 0

In [59]:
# Extract hour from Time
df['Hour'] = df['Time'].apply(
    lambda x: x.hour if pd.notnull(x) else None
)

# Create time period
def get_time_period(hour):
    if pd.isnull(hour):
        return 'Unknown'
    elif hour < 12:
        return 'Morning'
    elif hour < 17:
        return 'Afternoon'
    elif hour < 21:
        return 'Evening'
    else:
        return 'Night'

df['Time_Period'] = df['Hour'].apply(get_time_period)

# Check results
display(df[['Time', 'Hour', 'Time_Period']].head(10))

       Time  Hour Time_Period
0  13:08:00    13   Afternoon
1  10:29:00    10     Morning
2  13:23:00    13   Afternoon
3  20:33:00    20     Evening
4  10:37:00    10     Morning
5  18:30:00    18     Evening
6  14:36:00    14   Afternoon
7  11:38:00    11     Morning
8  17:15:00    17     Evening
9  13:27:00    13   Afternoon

In [60]:
# Rebuild FactSales with corrected Time fields

fact_sales = df_valid.copy()

fact_sales = fact_sales.merge(
    dim_date[['Date_Key', 'Date']],
    on='Date',
    how='left'
)

fact_sales = fact_sales.merge(
    dim_branch,
    on=['Branch', 'City'],
    how='left'
)

fact_sales = fact_sales.merge(
    dim_product,
    on='Product_Line',
    how='left'
)

fact_sales = fact_sales.merge(
    dim_customer,
    on=['Customer_Type', 'Gender'],
    how='left'
)

fact_sales = fact_sales.merge(
    dim_payment,
    on='Payment',
    how='left'
)

In [61]:
fact_sales = fact_sales[
    [
        'Invoice_ID',
        'Date_Key',
        'Branch_Key',
        'Product_Key',
        'Customer_Key',
        'Payment_Key',
        'Time',
        'Hour',
        'Time_Period',
        'Unit_Price',
        'Quantity',
        'Tax_5',
        'Sales',
        'COGS',
        'Gross_Margin_Percentage',
        'Gross_Income',
        'Rating'
    ]
]

display(fact_sales.head())

,Invoice_ID,Date_Key,Branch_Key,Product_Key,Customer_Key,Payment_Key,Time,Hour,Time_Period,Unit_Price,Quantity,Tax_5,Sales,COGS,Gross_Margin_Percentage,Gross_Income,Rating
0,750-67-8428,5,1,1,1,1,NaT,None,Unknown,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,226-31-3081,67,2,2,2,2,NaT,None,Unknown,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,631-41-3108,62,1,3,2,3,NaT,None,Unknown,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,123-19-1176,27,1,1,1,1,NaT,None,Unknown,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,373-73-7910,39,1,4,1,1,NaT,None,Unknown,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3

In [62]:
# Re-create valid dataframe using corrected df

valid_sales = df['Sales'] > 0
valid_quantity = df['Quantity'] > 0
valid_price = df['Unit_Price'] > 0
valid_rating = df['Rating'].between(1, 10)

all_valid = (
    valid_sales &
    valid_quantity &
    valid_price &
    valid_rating
)

df_valid = df[all_valid].copy()

print("Valid records:", len(df_valid))

display(
    df_valid[
        ['Time', 'Hour', 'Time_Period']
    ].head()
)

Valid records: 1000

       Time  Hour Time_Period
0  13:08:00    13   Afternoon
1  10:29:00    10     Morning
2  13:23:00    13   Afternoon
3  20:33:00    20     Evening
4  10:37:00    10     Morning

In [63]:
# Rebuild FactSales using corrected df_valid

fact_sales = df_valid.copy()

fact_sales = fact_sales.merge(
    dim_date[['Date_Key', 'Date']],
    on='Date',
    how='left'
)

fact_sales = fact_sales.merge(
    dim_branch,
    on=['Branch', 'City'],
    how='left'
)

fact_sales = fact_sales.merge(
    dim_product,
    on='Product_Line',
    how='left'
)

fact_sales = fact_sales.merge(
    dim_customer,
    on=['Customer_Type', 'Gender'],
    how='left'
)

fact_sales = fact_sales.merge(
    dim_payment,
    on='Payment',
    how='left'
)

print("FactSales rebuilt successfully!")

FactSales rebuilt successfully!

In [64]:
fact_sales = fact_sales[
    [
        'Invoice_ID',
        'Date_Key',
        'Branch_Key',
        'Product_Key',
        'Customer_Key',
        'Payment_Key',
        'Time',
        'Hour',
        'Time_Period',
        'Unit_Price',
        'Quantity',
        'Tax_5',
        'Sales',
        'COGS',
        'Gross_Margin_Percentage',
        'Gross_Income',
        'Rating'
    ]
]

display(fact_sales.head())

,Invoice_ID,Date_Key,Branch_Key,Product_Key,Customer_Key,Payment_Key,Time,Hour,Time_Period,Unit_Price,Quantity,Tax_5,Sales,COGS,Gross_Margin_Percentage,Gross_Income,Rating
0,750-67-8428,5,1,1,1,1,13:08:00,13,Afternoon,74.69,7,26.1415,548.9715,522.83,4.761905,26.1415,9.1
1,226-31-3081,67,2,2,2,2,10:29:00,10,Morning,15.28,5,3.8200,80.2200,76.40,4.761905,3.8200,9.6
2,631-41-3108,62,1,3,2,3,13:23:00,13,Afternoon,46.33,7,16.2155,340.5255,324.31,4.761905,16.2155,7.4
3,123-19-1176,27,1,1,1,1,20:33:00,20,Evening,58.22,8,23.2880,489.0480,465.76,4.761905,23.2880,8.4
4,373-73-7910,39,1,4,1,1,10:37:00,10,Morning,86.31,7,30.2085,634.3785,604.17,4.761905,30.2085,5.3

In [65]:
key_columns = [
    'Date_Key',
    'Branch_Key',
    'Product_Key',
    'Customer_Key',
    'Payment_Key'
]

print("Missing values in keys:")
print(fact_sales[key_columns].isnull().sum())

Missing values in keys:
Date_Key        0
Branch_Key      0
Product_Key     0
Customer_Key    0
Payment_Key     0
dtype: int64

In [66]:
import os

# Create output folder
os.makedirs('supermarket_data_warehouse', exist_ok=True)

# Save dimension tables
dim_date.to_csv(
    'supermarket_data_warehouse/dim_date.csv',
    index=False
)

dim_branch.to_csv(
    'supermarket_data_warehouse/dim_branch.csv',
    index=False
)

dim_product.to_csv(
    'supermarket_data_warehouse/dim_product.csv',
    index=False
)

dim_customer.to_csv(
    'supermarket_data_warehouse/dim_customer.csv',
    index=False
)

dim_payment.to_csv(
    'supermarket_data_warehouse/dim_payment.csv',
    index=False
)

# Save fact table
fact_sales.to_csv(
    'supermarket_data_warehouse/fact_sales.csv',
    index=False
)

print("ETL pipeline completed successfully!")

ETL pipeline completed successfully!

In [67]:
print("===== DATA WAREHOUSE SUMMARY =====")

print("DimDate     :", dim_date.shape)
print("DimBranch   :", dim_branch.shape)
print("DimProduct  :", dim_product.shape)
print("DimCustomer :", dim_customer.shape)
print("DimPayment  :", dim_payment.shape)
print("FactSales   :", fact_sales.shape)

===== DATA WAREHOUSE SUMMARY =====
DimDate     : (89, 9)
DimBranch   : (3, 3)
DimProduct  : (6, 2)
DimCustomer : (4, 3)
DimPayment  : (3, 2)
FactSales   : (1000, 17)

In [ ]:
import shutil

shutil.make_archive(
    'supermarket_data_warehouse',
    'zip',
    'supermarket_data_warehouse'
)

print("ZIP file created successfully!")